"""
Streamlit web UI for the RAG chatbot.

Run with:
    streamlit run app.py

Features:
  - Chat interface with message history.
  - Upload your own documents (PDF / TXT / MD) and (re)build the index.
  - Each answer shows the source chunks it was grounded in.
"""

from __future__ import annotations

from pathlib import Path

import streamlit as st

from src.config import config
from src.ingest import ingest

# --------------------------------------------------------------------------
# Page setup
# --------------------------------------------------------------------------
st.set_page_config(page_title="RAG Chatbot", page_icon="📚", layout="wide")
st.title("📚 RAG Chatbot: DC, Marvel, Batman 🦇")
st.caption(
    "Ask questions about your own documents. Answers are generated by "
    "Llama and grounded in the documents you provide."
)


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------
def index_exists() -> bool:
    return config.vector_store_dir.exists() and any(
        config.vector_store_dir.iterdir()
    )


@st.cache_resource(show_spinner=False)
def get_bot():
    """Load the RAG chatbot once and cache it across reruns."""
    # Imported lazily so the app can render even before an index exists.
    from src.rag_engine import RAGChatbot

    return RAGChatbot()


def save_uploaded_files(uploaded_files) -> int:
    """Persist uploaded files into the data directory. Returns count saved."""
    config.data_dir.mkdir(parents=True, exist_ok=True)
    saved = 0
    for uf in uploaded_files:
        dest = config.data_dir / uf.name
        dest.write_bytes(uf.getbuffer())
        saved += 1
    return saved


# --------------------------------------------------------------------------
# Sidebar: configuration + document management
# --------------------------------------------------------------------------
with st.sidebar:
    st.header("⚙️ Setup")

    backend_label = (
        f"**LLM backend:** `{config.llm_backend}`  \n"
        f"**Model:** `{config.ollama_model if config.llm_backend == 'ollama' else config.groq_model}`"
    )
    st.markdown(backend_label)
    st.divider()

    st.subheader("1. Add documents")
    uploads = st.file_uploader(
        "Upload PDF, TXT, or Markdown files",
        type=["pdf", "txt", "md"],
        accept_multiple_files=True,
    )
    if uploads:
        if st.button("💾 Save uploaded files", use_container_width=True):
            n = save_uploaded_files(uploads)
            st.success(f"Saved {n} file(s) to the data folder.")

    st.subheader("2. Build the knowledge base")
    st.caption(
        "Embeds every document in the data folder into the vector store. "
        "Run this after adding or changing documents."
    )
    if st.button("🔨 Rebuild index", use_container_width=True):
        with st.spinner("Ingesting documents (first run downloads the "
                        "embedding model)..."):
            try:
                n_chunks = ingest(rebuild=True)
                get_bot.clear()  # drop cached bot so it reloads the new index
                st.session_state.pop("messages", None)
                st.success(f"Indexed {n_chunks} chunk(s). Ready to chat!")
            except Exception as exc:  # noqa: BLE001
                st.error(f"Ingestion failed: {exc}")

    st.divider()
    if index_exists():
        st.success("Knowledge base is ready.")
    else:
        st.warning("No index yet. Add documents and click **Rebuild index**.")


# --------------------------------------------------------------------------
# Main chat area
# --------------------------------------------------------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []

# Replay history.
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("sources"):
            with st.expander("📎 Sources"):
                for i, src in enumerate(msg["sources"], start=1):
                    st.markdown(f"**{i}. {src['source']}**")
                    st.caption(src["preview"])

# Chat input.
prompt = st.chat_input("Ask a question about your documents...")

if prompt:
    if not index_exists():
        st.error("Please build the knowledge base first (see the sidebar).")
    else:
        # Show the user's message.
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Generate the answer.
        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                try:
                    bot = get_bot()
                    result = bot.ask(prompt)
                    st.markdown(result.answer)

                    sources = [
                        {
                            "source": d.metadata.get("source", "unknown"),
                            "preview": d.page_content[:300].replace("\n", " ")
                            + "...",
                        }
                        for d in result.sources
                    ]
                    if sources:
                        with st.expander("📎 Sources"):
                            for i, src in enumerate(sources, start=1):
                                st.markdown(f"**{i}. {src['source']}**")
                                st.caption(src["preview"])

                    st.session_state.messages.append(
                        {
                            "role": "assistant",
                            "content": result.answer,
                            "sources": sources,
                        }
                    )
                except Exception as exc:  # noqa: BLE001
                    st.error(
                        f"Something went wrong: {exc}\n\n"
                        "If you're using Ollama, make sure it's running and "
                        "the model is pulled (`ollama pull llama3.1:8b`)."
                    )
